import { useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Building2, CalendarDays, CheckCircle2, ChevronRight, ExternalLink, MapPin, ShieldCheck, Sparkles, Tag, UserRound, Wallet } from 'lucide-react';
import { useApp } from '../context/AppContext';
import ItemCard from '../components/ItemCard';

export default function ItemDetailPage() {
  const { id } = useParams();
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const { items, requests, isLoggedIn, createRequest } = useApp();
  const [error,setError]=useState('');
  const [tab,setTab]=useState<'info'|'location'>('info');
  const item=items.find(i=>i.id===id);
  if(!item) return <div className="page-container empty-state"><Wallet size={36}/><h1>이 물품을 찾을 수 없어요.</h1><p>삭제되었거나 잘못된 물품 주소예요.</p><Link to="/search" className="button button-primary">물품 목록으로</Link></div>;
  const existing=requests.find(r=>r.itemId===item.id && r.status!=='rejected');
  const related=items.filter(i=>i.id!==item.id && i.category===item.category).slice(0,4);
  const requestReturn=()=>{
    if(!isLoggedIn){navigate(`/login?returnTo=${encodeURIComponent(`/items/${item.id}${params.size?'?'+params.toString():''}`)}`);return;}
    try { const request=existing??createRequest(item.id,params.get('lostItem')??undefined);navigate(`/returns/${request.id}`); } catch(e) {setError(e instanceof Error?e.message:'반환 요청을 처리하지 못했어요. 다시 시도해 주세요.');}
  };
  return <div className="page-container detail-page"><div className="breadcrumbs"><Link to="/">홈</Link><ChevronRight size={13}/><Link to="/search">전국 통합 검색</Link><ChevronRight size={13}/><span>물품 상세</span></div><div className="detail-layout"><div><div className="detail-photo"><img src={item.image} alt={`${item.title} 예시 이미지`}/><span className="photo-counter">1 / 1</span></div><p className="sample-caption">프로토타입용 가상 물품 · 예시 이미지</p></div><div className="detail-info"><div className="detail-badges"><span className={`badge ${item.type==='found'?'badge-green':'badge-blue'}`}>{item.type==='found'?'주인을 찾아요':'찾고 있어요'}</span><span className="badge badge-neutral">{item.source==='public'?'공공데이터 예시':'자체 등록'}</span>{item.status==='returned'&&<span className="badge badge-green"><CheckCircle2 size={12}/>반환 완료</span>}</div><h1>{item.title}</h1><p className="detail-subtitle"><MapPin size={16}/>{item.location.startsWith(item.region) ? item.location : [item.region, item.location].join(' ')}</p><dl className="detail-facts"><div><dt><Tag size={17}/>카테고리</dt><dd>{item.category}</dd></div><div><dt><Wallet size={17}/>색상</dt><dd>{item.color}</dd></div><div><dt><CalendarDays size={17}/>{item.type==='found'?'습득 날짜':'분실 날짜'}</dt><dd>{item.date.replaceAll('-','. ')}</dd></div><div><dt><UserRound size={17}/>등록 출처</dt><dd>{item.source==='public'?'공공 보관기관 (가상)':'LOST QUEST 이웃 (테스트)'}</dd></div></dl>
      {item.source==='public'?<div className="agency-card"><Building2 size={22}/><div><strong>{item.agency??'공식 보관기관'}</strong><p>이 물품은 외부 기관의 보관 물품 예시예요. 실제 반환 절차는 공식 사이트에서 확인해 주세요.</p><a href="https://www.lost112.go.kr/" target="_blank" rel="noopener noreferrer" className="button button-primary">경찰청 LOST112 안내<ExternalLink size={15}/></a><small>외부 사이트로 이동합니다. 이 예시 물품과 연결되지 않습니다.</small></div></div>:item.type==='found'?<><div className="detail-security"><ShieldCheck size={19}/><p>소중한 물건을 안전하게 돌려드려요.<br/><strong>비공개 특징 확인과 QR 인증</strong> 후 반환을 진행해요.</p></div><button onClick={requestReturn} disabled={item.status==='returned'&&!existing} className="button button-primary detail-cta">{existing?'반환 진행 상황 보기':item.status==='returned'?'반환이 완료된 물품':'내 물건이라면, 반환 요청하기'}<ArrowRight size={17}/></button>{error&&<p className="field-error" role="alert">{error}</p>}</>:<div className="detail-security detail-lost-message"><Sparkles size={23}/><div><strong>{item.status === 'returned' ? '소중한 물건이 돌아왔어요.' : item.createdBy === 'demo' ? '닮은 물품을 함께 찾아볼까요?' : '이웃이 찾고 있는 물건이에요.'}</strong><p>{item.status === 'returned' ? '마이페이지에서 반환 내역을 확인할 수 있어요.' : item.createdBy === 'demo' ? '등록한 정보를 바탕으로 습득물 후보를 비교해 보세요.' : '습득한 물품을 등록하면 함께 찾아볼 수 있어요.'}</p>{item.status === 'open' && item.createdBy === 'demo' && <Link className="button button-primary" to={`/matches?item=${item.id}`}>AI 매칭 확인하기<ArrowRight size={16}/></Link>}</div></div>}
    </div></div><section className="detail-description card"><div className="detail-tabs" role="tablist" aria-label="물품 상세 정보"><button role="tab" aria-selected={tab==='info'} aria-controls="detail-panel" id="detail-tab-info" className={tab==='info'?'active':''} onClick={()=>setTab('info')}>상세 정보</button><button role="tab" aria-selected={tab==='location'} aria-controls="detail-panel" id="detail-tab-location" className={tab==='location'?'active':''} onClick={()=>setTab('location')}>위치 정보</button></div><div id="detail-panel" role="tabpanel" aria-labelledby={`detail-tab-${tab}`} className="detail-tab-body">{tab==='info'?<><h2>이런 물건이에요</h2><p>{item.description}</p><div className="info-note"><ShieldCheck size={17}/><p>안전한 소유 확인을 위해 일부 특징은 공개되지 않아요. 반환 요청 단계에서 확인해 주세요.</p></div></>:<><div className="location-placeholder"><MapPin size={34}/><strong>{item.location.startsWith(item.region) ? item.location : [item.region, item.location].join(' ')}</strong><span>위치 텍스트 예시 · 실제 지도 API는 연결하지 않았어요</span></div><p>정확한 수령 장소는 실제 서비스에서 반환 요청 승인 후 안내됩니다.</p></>}</div></section><Link to="/search" className="text-link detail-back"><ArrowLeft size={16}/>물품 목록으로 돌아가기</Link>{related.length>0&&<section className="detail-related"><div className="section-heading"><div><span className="section-kicker">다른 물건도 살펴보세요</span><h2>비슷한 카테고리의 물품</h2></div></div><div className="items-grid">{related.map(i=><ItemCard key={i.id} item={i}/>)}</div></section>}</div>;
}
